parameters:
#    php_bb_logging_admin_interface.example.class: phpBB\LoggingAdminInterfaceBundle\Example

services:
#    php_bb_logging_admin_interface.example:
#        class: %php_bb_logging_admin_interface.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
